const suggestions = {
  'Languages': [
    'JavaScript',
    'Python',
    'Ruby',
    'C',
    'C++',
    'C#',
    'Java',
    'Go',
    'Rust',
    'Swift',
    'Kotlin',
    'PHP',
    'TypeScript',
    'Dart',
    'Haskell',
    'Elixir',
    'Erlang',
    'Scala',
    'Clojure',
  ],
  'Frameworks': [
    'Next.js',
    'Gatsby',
    'Nuxt',
    'Laravel',
    'Spring',
    'Django',
    'Flask',
    'Express.js',
    'Vue.js',
    'Angular',
    'React',
    'Styled Components',
    'Tailwind',
    'Bootstrap',
  ],
  'Databases': [
    'PostgreSQL',
    'MySQL',
    'MariaDB',
    'SQLite',
    'CockroachDB',
    'Firebase',
    'Cassandra',
    'DynamoDB',
    'Redis',
    'MongoDB',
    'Neo4j',
    'Dgraph',
    'ArangoDB',
    'Kibana',
  ],
  'Design': [
    'UI/UX',
    'Graphic Design',
    'Logo Design',
    'Branding',
    'Typography',
    'Color Theory',
    'Layout',
    'Wireframing',
    'Prototyping',
    'User Testing',
    'User Research',
    'Accessibility',
    'Information Architecture',
  ],
  'General': [
    'Team Player',
    'Leadership',
    'Self-Starter',
    'Problem Solver',
    'Fast Learner',
    'Detail Oriented',
    'Creative',
    'Adaptable',
    'Collaborative',
    'Organized',
    'Motivated',
    'Dependable',
    'Flexible',
    'Hardworking',
    'Dedicated',
    'Ambitious',
    'Enthusiastic',
    'Positive Attitude',
    'Punctual',
    'Honest',
  ],
}

export default suggestions